import * as fs from "node:fs";
import * as path from "node:path";
import { resolveDocSearchHome } from "../core/indexLocation.js";

/**
 * Stable launcher scripts under `~/.doc-search/bin/`.
 *
 * A `.mcp.json` generated against the extension's install dir embeds a
 * versioned absolute path (`…/de-otio.mcp-doc-search-X.Y.Z/dist/mcp-server.js`)
 * that silently breaks on every extension upgrade — and the activation-time
 * repair in `mcpJson.ts` only reaches workspaces that are actually opened in
 * VS Code afterwards. The launchers break that cycle: each is a tiny
 * `require()` forwarder at a version-independent path, rewritten on every
 * activation to target the currently installed build, so a `.mcp.json` (or a
 * shell PATH entry) pointing at it survives upgrades in every workspace at
 * once.
 *
 * A forwarder file is used instead of a symlink because symlink creation on
 * Windows needs elevated rights or developer mode; `require()` of an absolute
 * path behaves identically and Node resolves the target's own imports
 * relative to the real dist directory either way.
 */

const LAUNCHER_NAMES = ["mcp-server.js", "mcp-doc-search.js"] as const;

/** Directory holding the stable launchers (respects `DOC_SEARCH_HOME`). Pure. */
export function stableBinDir(env: NodeJS.ProcessEnv = process.env): string {
  return path.join(resolveDocSearchHome(env), "bin");
}

/** Source text of a launcher forwarding to `realPath`. Pure. */
export function launcherSource(realPath: string): string {
  return [
    "#!/usr/bin/env node",
    "// Generated by the mcp-doc-search extension on activation — do not edit.",
    "// Stable entry point: forwards to the currently installed extension build",
    "// so .mcp.json files and PATH entries survive version upgrades.",
    `require(${JSON.stringify(realPath)});`,
    "",
  ].join("\n");
}

/**
 * Write (or refresh) the stable launchers so they forward to the build at
 * `extensionDir`. Idempotent: unchanged launchers are left untouched.
 * Best-effort; returns the stable `mcp-server.js` path, or undefined when the
 * bin directory could not be written (callers then fall back to the versioned
 * path). Never throws.
 */
export function writeStableLaunchers(
  extensionDir: string,
  env: NodeJS.ProcessEnv = process.env,
): string | undefined {
  try {
    const binDir = stableBinDir(env);
    fs.mkdirSync(binDir, { recursive: true });
    for (const name of LAUNCHER_NAMES) {
      const launcherPath = path.join(binDir, name);
      const source = launcherSource(path.join(extensionDir, "dist", name));
      let current: string | undefined;
      try {
        current = fs.readFileSync(launcherPath, "utf8");
      } catch {
        current = undefined;
      }
      if (current !== source) fs.writeFileSync(launcherPath, source, { mode: 0o755 });
    }
    return path.join(binDir, "mcp-server.js");
  } catch {
    return undefined;
  }
}
